import './globals.css'
import { Navbar } from '../components'
import { Bitter } from 'next/font/google'

const bitter = Bitter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bitter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
